spring:
  application:
    name:
      ProductService
  jpa:
    hibernate:
      ddl-auto=create

  flyway:
    locations: classpath:db/migration
    enabled: true

  datasource:
    url:
      jdbc:mysql://${MYSQL_HOST:localhost}:3306/Product
    username:
      root
    password:
      1108
    driver-class-name:
      com.mysql.cj.jdbc.Driver