server:
  port: 8084

spring:
  application:
    name: UserService

  flyway:
    locations: classpath:db/migration
    enabled: true

  datasource:
    url:
      jdbc:mysql://${MYSQL_HOST:localhost}:3306/User
    username:
      root
    password:
      1108
    driver-class-name:
      com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    enabled: true

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000

#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html