server:
  port: 8080



spring:
#  main:
#    web-application-type: reactive
  application:
    name: GatewayService
  cloud:
    gateway:
      routes:
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=3

        - id: marketplace-service-route
          uri: lb://marketplace-service
          predicates:
            - Path=/marketplace/**
          filters:
            - StripPrefix=3

        - id: auth-service-route
          uri: lb://UserService
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

eureka:
  client:
    healthcheck:
      enabled: true
logging:
  level:
    org.springframework: debug

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    prefix: "Bearer"

#springdoc:
#  api-docs:
#    path: /api-docs              # ???? ??? ????????? OpenAPI ????????????
#    enable: true                       # ???????? ????????? ????????????
#  swagger-ui:
#    path: /swagger-ui.html              # ???? ??? ??????? ? Swagger UI
#    enabled: true                       # ???????? Swagger UI
#    urls:
#      - url: /api-docs                  # URL ??? ????????? ???????????? ?? gateway-service
#        name: Gateway Service           # ??? ??? ??????????? ? Swagger UI
#      - url: /api/v1/products/api-docs     # URL ??? ????????? ???????????? ?? product-service
#        name: Book Service              # ??? ??? ??????????? ? Swagger UI
#      - url: /api/v1/library/api-docs   # URL ??? ????????? ???????????? ?? library-service
#        name: Library Service           # ??? ??? ??????????? ? Swagger UI
#      - url: /auth/api-docs             # URL ??? ????????? ???????????? ?? auth-service
#        name: Auth Service              # ??? ??? ??????????? ? Swagger UI